### ISSUE TITLE
Feature Request: Random Access to documents

### ISSUE THREAD

**Issue by mam10eks** [heinrichreimer/chatnoir-api#1]
Thanks for providing this nice API!

One feature of ChatNoir that I use quite often is the random access to documents from ClueWeb09 and ClueWeb12.

Would you think it is difficult to add this feature to this library (maybe in an API similar to the DocStore of `ir_datasets`)?

**Comment by heinrichreimer** [comment]
That should be simple to implement with the existing `html_contents()` function:
https://github.com/heinrichreimer/chatnoir-api/blob/2aeb6e4b7487115fc991d05eaf5f2553130b52b4/chatnoir_api/__init__.py#L14

All we need to do is port the behavior of [webis-uuid](https://github.com/chatnoir-eu/webis-uuid)'s
`generateUUID()` in Python.

**Comment by heinrichreimer** [comment]
New signature:
https://github.com/heinrichreimer/chatnoir-api/blob/2d55afb022640483bb702126635b7838f21ca051/chatnoir_api/html.py#L10-L14
The function automatically generates the `UUID` if a `str` (document ID) is given.
